# Generated by Django 4.0.4 on 2023-03-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetexpense',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
