# Generated by Django 4.0.4 on 2023-03-01 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budgetexpense_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetexpense',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='budget.budget'),
        ),
    ]
