# Generated by Django 4.0.4 on 2023-02-28 23:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_alter_purchase_etf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etf',
            name='sharpe_ratio_3yr',
            field=models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
