# Generated by Django 4.0.4 on 2023-03-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_exchange_exchangehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangehistory',
            options={'verbose_name': 'Exchange History', 'verbose_name_plural': 'Exchange Histories'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Etf Purchase', 'verbose_name_plural': 'Etf Purchases'},
        ),
    ]
